# not for submission, just to create the database from the CSV file - generated by Claude

import sqlite3
import codecs

# Connect to (or create) the database
conn = sqlite3.connect('comp3208_20m.db')
c = conn.cursor()

# Create the table
c.execute('''
    CREATE TABLE IF NOT EXISTS ratings (
        UserID   INT,
        ItemID   INT,
        Rating   FLOAT,
        Timestamp INT
    )
''')
conn.commit()

# Clear any existing data
c.execute('DELETE FROM ratings')
conn.commit()

# Read and insert in batches for speed
BATCH_SIZE = 10000
batch = []

with codecs.open('csv/train_20M_withratings.csv', 'r', 'utf-8', errors='replace') as f:
    for i, line in enumerate(f):
        line = line.strip()
        if not line:
            continue
        parts = line.split(',')
        if len(parts) == 4:
            batch.append((parts[0], parts[1], parts[2], parts[3]))
        
        # Insert in chunks of 10,000 rows at a time
        if len(batch) >= BATCH_SIZE:
            c.executemany('INSERT INTO ratings VALUES (?,?,?,?)', batch)
            conn.commit()
            batch = []
            
        if i % 500000 == 0:
            print(f'Processed {i:,} rows...')

# Insert any remaining rows
if batch:
    c.executemany('INSERT INTO ratings VALUES (?,?,?,?)', batch)
    conn.commit()

# Add an index for fast lookups by user or item
c.execute('CREATE INDEX IF NOT EXISTS idx_user ON ratings (UserID)')
c.execute('CREATE INDEX IF NOT EXISTS idx_item ON ratings (ItemID)')
conn.commit()

print('Done! Database ready.')
c.close()
conn.close()